#! /hint/sh

NINJAFLAGS="-d stats -w phonycycle=err"

if ! [ -z "$_march" ]; then
    march="-march=$_march"
fi

export CC="gcc -m32 -Wno-missing-profile -Wno-nonnull-compare"
export CXX="g++ -m32 -Wno-missing-profile -Wno-nonnull-compare"
export PKG_CONFIG="/usr/bin/i686-pc-linux-gnu-pkg-config"
export CFLAGS="$march -Ofast -falign-functions=32 -fno-semantic-interposition -mprefer-vector-width=256"
export CXXFLAGS="$march -Ofast -falign-functions=32 -fno-semantic-interposition -mprefer-vector-width=256"
export LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
