#! /hint/sh

_set_required_number_fds()
{
    DEFAULT_FD_NUMBER=$(ulimit -n)
    ulimit -n 8192
}

_write_native_file()
{
    if [ "${_use_clang}" ]; then
        export NATIVE_FILE="${startdir}/clang.native"

		cat <<-EOF > "${NATIVE_FILE}"
			#! /hint/toml

			[binaries]
			c = ['/usr/bin/clang', '-m32']
			cpp = ['/usr/bin/clang++', '-m32']
			ar = '/usr/bin/llvm-ar'
			strip = '/usr/bin/llvm-strip'
			llvm-config = '/usr/bin/llvm-config32'
			pkg-config = '/usr/bin/i686-pc-linux-gnu-pkg-config'
		EOF
    else
        export NATIVE_FILE="${startdir}/gcc.native"
		cat <<-EOF > "${NATIVE_FILE}"
			#! /hint/toml

			[binaries]
			c = ['/usr/bin/gcc', '-m32']
			cpp = ['/usr/bin/g++', '-m32']
			ar = '/usr/bin/ar'
			strip = '/usr/bin/strip'
			llvm-config = '/usr/bin/llvm-config32'
			pkg-config = '/usr/bin/i686-pc-linux-gnu-pkg-config'
		EOF
    fi
}

_no_pgo_build()
{
    meson setup mesa _build                                                                             \
        --strip                                                                                         \
        --native-file "${NATIVE_FILE}"                                                                  \
        -D b_ndebug='false'                                                                             \
        -D b_lto='true'                                                                                 \
        -D buildtype='plain'                                                                            \
        --wrap-mode='nofallback'                                                                        \
        -D prefix='/usr'                                                                                \
        -D sysconfdir='/etc'                                                                            \
        --libdir='/usr/lib32'                                                                           \
        -D platforms='x11,wayland'                                                                      \
        -D dri-drivers='i915,i965,r200,r100,nouveau'                                                    \
        -D gallium-drivers='r300,r600,radeonsi,nouveau,svga,softpipe,llvmpipe,virgl,iris,zink,crocus'   \
        -D vulkan-drivers='amd,intel'                                                                   \
        -D egl='enabled'                                                                                \
        -D gallium-extra-hud='true'                                                                     \
        -D vulkan-layers='device-select,overlay'                                                        \
        -D gallium-opencl='disabled'                                                                    \
        -D gallium-va='enabled'                                                                         \
        -D gallium-vdpau='enabled'                                                                      \
        -D gallium-xa='enabled'                                                                         \
        -D gallium-xvmc='disabled'                                                                      \
        -D gbm='enabled'                                                                                \
        -D gles1='disabled'                                                                             \
        -D gles2='enabled'                                                                              \
        -D glvnd='enabled'                                                                              \
        -D glx='dri'                                                                                    \
        -D libunwind='enabled'                                                                          \
        -D llvm='enabled'                                                                               \
        -D lmsensors='enabled'                                                                          \
        -D osmesa='true'                                                                                \
        -D shared-glapi='enabled'                                                                       \
        -D valgrind='disabled'                                                                          \
        -D tools=[]                                                                                     \
        -D zstd='enabled'                                                                               \
        -D microsoft-clc='disabled'

    meson configure --no-pager _build

    ninja ${NINJAFLAGS} -C _build
}

_generate_pgo_build()
{
    meson setup mesa "${pgo_build_dir}"                                                                 \
        --strip                                                                                         \
        --native-file "${NATIVE_FILE}"                                                                  \
        -D b_ndebug='false'                                                                             \
        -D b_lto='true'                                                                                 \
        -D b_pgo='generate'                                                                             \
        -D buildtype='plain'                                                                            \
        --wrap-mode='nofallback'                                                                        \
        -D prefix='/usr'                                                                                \
        -D sysconfdir='/etc'                                                                            \
        --libdir='/usr/lib32'                                                                           \
        -D platforms='x11,wayland'                                                                      \
        -D dri-drivers='i915,i965,r200,r100,nouveau'                                                    \
        -D gallium-drivers='r300,r600,radeonsi,nouveau,svga,softpipe,llvmpipe,virgl,iris,zink,crocus'   \
        -D vulkan-drivers='amd,intel'                                                                   \
        -D egl='enabled'                                                                                \
        -D gallium-extra-hud='true'                                                                     \
        -D vulkan-layers='device-select,overlay'                                                        \
        -D gallium-opencl='disabled'                                                                    \
        -D gallium-va='enabled'                                                                         \
        -D gallium-vdpau='enabled'                                                                      \
        -D gallium-xa='enabled'                                                                         \
        -D gallium-xvmc='disabled'                                                                      \
        -D gbm='enabled'                                                                                \
        -D gles1='disabled'                                                                             \
        -D gles2='enabled'                                                                              \
        -D glvnd='enabled'                                                                              \
        -D glx='dri'                                                                                    \
        -D libunwind='enabled'                                                                          \
        -D llvm='enabled'                                                                               \
        -D lmsensors='enabled'                                                                          \
        -D osmesa='true'                                                                                \
        -D shared-glapi='enabled'                                                                       \
        -D valgrind='disabled'                                                                          \
        -D tools=[]                                                                                     \
        -D zstd='enabled'                                                                               \
        -D microsoft-clc='disabled'

    meson configure --no-pager "${pgo_build_dir}"

    ninja ${NINJAFLAGS} -C "${pgo_build_dir}"
}

_use_pgo_build()
{
    meson setup mesa "${pgo_build_dir}"                                                                 \
        --strip                                                                                         \
        --native-file "${NATIVE_FILE}"                                                                  \
        -D b_ndebug='false'                                                                             \
        -D b_lto='true'                                                                                 \
        -D b_pgo='use'                                                                                  \
        -D buildtype='plain'                                                                            \
        --wrap-mode='nofallback'                                                                        \
        -D prefix='/usr'                                                                                \
        -D sysconfdir='/etc'                                                                            \
        --libdir='/usr/lib32'                                                                           \
        -D platforms='x11,wayland'                                                                      \
        -D dri-drivers='i915,i965,r200,r100,nouveau'                                                    \
        -D gallium-drivers='r300,r600,radeonsi,nouveau,svga,softpipe,llvmpipe,virgl,iris,zink,crocus'   \
        -D vulkan-drivers='amd,intel'                                                                   \
        -D egl='enabled'                                                                                \
        -D gallium-extra-hud='true'                                                                     \
        -D vulkan-layers='device-select,overlay'                                                        \
        -D gallium-opencl='disabled'                                                                    \
        -D gallium-va='enabled'                                                                         \
        -D gallium-vdpau='enabled'                                                                      \
        -D gallium-xa='enabled'                                                                         \
        -D gallium-xvmc='disabled'                                                                      \
        -D gbm='enabled'                                                                                \
        -D gles1='disabled'                                                                             \
        -D gles2='enabled'                                                                              \
        -D glvnd='enabled'                                                                              \
        -D glx='dri'                                                                                    \
        -D libunwind='enabled'                                                                          \
        -D llvm='enabled'                                                                               \
        -D lmsensors='enabled'                                                                          \
        -D osmesa='true'                                                                                \
        -D shared-glapi='enabled'                                                                       \
        -D valgrind='disabled'                                                                          \
        -D tools=[]                                                                                     \
        -D zstd='enabled'                                                                               \
        -D microsoft-clc='disabled'

    meson configure --no-pager "${pgo_build_dir}"

    ninja ${NINJAFLAGS} -C "${pgo_build_dir}"
}
